name: Build and Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t frontend:latest .

      - name: Stop and remove existing container
        run: |
          docker stop frontend || true
          docker rm frontend || true

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 --name frontend frontend:latest
